name: Feature Request
description: Suggest an idea for this project
labels: "Type: Enhancement"
body:
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    description: A clear and concise description of what the problem is.
- type: textarea
  attributes:
    label: The solution you would like to have available
    description: A clear and concise description of what you want us to implement.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives you have considered
    description: A clear and concise description of any alternative solutions or features you have considered so far.
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
