name: Cancel CI of Draft PR

on:
  pull_request_target:

jobs:
  check:
    name: Check for draft PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@main
    
    - name: Check
      shell: bash
      run: |
        if [ ${{ github.event.pull_request.draft }} == true ]; then
          echo "⚠️ Detected Draft PR!"

          # Retrieve id and head sha of ongoing workflow runs
          gh run list --workflow "Continuous Integration" \
                      --json event,status,databaseId,headSha \
                      --jq '.[] | select((.event==\"pull_request\") and (.status==\"queued\") and (.status==\"in_progress\")) | [.databaseId, .headSha] | @tsv' > workflow_runs.txt

          echo "Ongoing workflow runs: ID and HEAD-SHA"
          cat workflow_runs.txt

          # Retrieve head sha of Draft PRs
          gh pr list --json isDraft,commits --jq '.[] | select(.isDraft) | .commits | last | .oid' > draft_prs.txt
          echo "Head-sha of Draft PRs"
          cat draft_prs.txt

          # Check ongoing workflow runs against Draft PRs
          for run in $(cat workflow_runs.txt); do
            run_id = $(echo ${run} | cut -d' ' -f1)
            run_sha = $(echo ${run} | cut -d' ' -f2)
            # Skip this workflow run
            if [ "${run_id}" != "${{ github.run_id }}" ]; then
              for pr_sha in $(cat draft_prs.txt); do
                if [ "${run_sha}" == "${pr_sha}" ]; then
                  echo "Cancelling workflow ${run_id}..."
                  gh run cancel ${run_id}
                  echo "❌ Workflow cancelled!"
                fi
              done
            fi
          done
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
