name: Cancel CI of Draft PR

on:
  pull_request_target:

jobs:
  check:
    name: Check for draft PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@main
    
    - name: Check
      shell: bash
      run: |
        if [ ${{ github.event.pull_request.draft }} == true ]; then
          echo "⚠️ Detected Draft PR!"

          # Retrieve id and head sha of ongoing workflow runs
          gh run list --workflow "Continuous Integration" \
                      --json event,status,databaseId,headSha \
                      --jq '.[] | select((.event=="pull_request") and (.status!="completed")) | [.databaseId, .headSha] | @tsv' > workflow_runs.txt

          echo "Ongoing workflow runs id and head-sha:"
          cat workflow_runs.txt
          echo ""

          # Retrieve head sha of Draft PRs
          gh pr list --json isDraft,commits --jq '.[] | select(.isDraft) | .commits | last | .oid' > draft_prs.txt
          echo "Draft PRs head-sha:"
          cat draft_prs.txt
          echo ""

          # Check ongoing workflow runs against Draft PRs
          while read -r run; do
            run_id=$(echo ${run} | cut -d' ' -f1)
            run_sha=$(echo ${run} | cut -d' ' -f2)
            if [ "${run_id}" != "${{ github.run_id }}" ]; then
              for pr_sha in $(cat draft_prs.txt); do
                if [ "${run_sha}" == "${pr_sha}" ]; then
                  echo "Cancelling workflow ${run_id}..."
                  gh run cancel ${run_id}
                  echo "❌ Workflow cancelled!"
                fi
              done
            fi
          done < workflow_runs.txt
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
